INSERT INTO locations (town, province) VALUES ('Aleksandrów Kujawski' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Aleksandrów Łódzki' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Alwernia' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Andrychów' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Annopol' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Augustów' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Babimost' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Baborów' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Baranów Sandomierski' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Barcin' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Barczewo' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Bardo' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Barlinek' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Bartoszyce' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Barwice' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Bełchatów' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Bełżyce' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Będzin' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Biała' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Biała Piska' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Biała Podlaska' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Biała Rawska' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Białobrzegi' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Białogard' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Biały Bór' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Białystok' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Biecz' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Bielawa' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Bielsk Podlaski' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Bielsko-Biała' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Bieruń' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Bierutów' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Bieżuń' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Biłgoraj' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Biskupiec' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Bisztynek' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Blachownia' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Błaszki' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Błażowa' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Błonie' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Bobolice' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Bobowa' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Bochnia' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Bodzentyn' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Bogatynia' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Boguchwała' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Boguszów-Gorce' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Bojanowo' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Bolesławiec' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Bolków' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Borek Wielkopolski' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Borne Sulinowo' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Braniewo' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Brańsk' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Brodnica' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Brok' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Brusy' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Brwinów' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Brzeg' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Brzeg Dolny' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Brzesko' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Brzeszcze' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Brześć Kujawski' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Brzeziny' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Brzostek' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Brzozów' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Buk' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Bukowno' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Busko-Zdrój' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Bychawa' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Byczyna' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Bydgoszcz' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Bystrzyca Kłodzka' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Bytom' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Bytom Odrzański' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Bytów' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Cedynia' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Chełm' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Chełmek' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Chełmno' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Chełmża' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Chęciny' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Chmielnik' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Chocianów' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Chociwel' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Chocz' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Chodecz' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Chodzież' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Chojna' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Chojnice' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Chojnów' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Choroszcz' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Chorzele' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Chorzów' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Choszczno' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Chrzanów' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Ciechanowiec' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Ciechanów' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Ciechocinek' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Cieszanów' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Cieszyn' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Ciężkowice' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Cybinka' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Czaplinek' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Czarna Białostocka' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Czarna Woda' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Czarne' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Czarnków' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Czchów' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Czechowice-Dziedzice' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Czeladź' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Czempiń' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Czerniejewo' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Czersk' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Czerwieńsk' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Czerwionka-Leszczyny' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Częstochowa' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Człopa' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Człuchów' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Czyżew' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Ćmielów' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Daleszyce' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Darłowo' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Dąbie' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Dąbrowa Białostocka' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Dąbrowa Górnicza' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Dąbrowa Tarnowska' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Debrzno' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Dębica' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Dęblin' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Dębno' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Dobczyce' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Dobiegniew' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Dobra' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Dobra' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Dobre Miasto' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Dobrodzień' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Dobrzany' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Dobrzyca' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Dobrzyń nad Wisłą' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Dolsk' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Drawno' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Drawsko Pomorskie' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Drezdenko' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Drobin' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Drohiczyn' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Drzewica' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Dukla' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Duszniki-Zdrój' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Dynów' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Działdowo' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Działoszyce' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Działoszyn' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Dzierzgoń' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Dzierżoniów' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Dziwnów' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Elbląg' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Ełk' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Frampol' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Frombork' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Garwolin' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Gąbin' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Gdańsk' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Gdynia' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Giżycko' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Glinojeck' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Gliwice' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Głogów' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Głogów Małopolski' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Głogówek' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Głowno' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Głubczyce' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Głuchołazy' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Głuszyca' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Gniew' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Gniewkowo' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Gniezno' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Gogolin' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Golczewo' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Goleniów' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Golina' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Golub-Dobrzyń' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Gołańcz' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Gołdap' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Goniądz' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Gorlice' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Gorzów Śląski' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Gorzów Wielkopolski' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Gostynin' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Gostyń' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Gościno' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Gozdnica' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Góra' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Góra Kalwaria' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Górowo Iławeckie' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Górzno' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Grabów nad Prosną' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Grajewo' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Grodków' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Grodzisk Mazowiecki' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Grodzisk Wielkopolski' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Grójec' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Grudziądz' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Grybów' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Gryfice' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Gryfino' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Gryfów Śląski' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Gubin' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Hajnówka' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Halinów' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Hel' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Hrubieszów' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Iława' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Iłowa' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Iłża' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Imielin' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Inowrocław' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Ińsko' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Iwonicz-Zdrój' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Izbica Kujawska' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Jabłonowo Pomorskie' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Janikowo' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Janowiec Wielkopolski' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Janów Lubelski' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Jarocin' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Jarosław' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Jasień' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Jasło' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Jastarnia' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Jastrowie' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Jastrzębie-Zdrój' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Jawor' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Jaworzno' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Jaworzyna Śląska' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Jedlicze' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Jedlina-Zdrój' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Jedwabne' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Jelcz-Laskowice' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Jelenia Góra' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Jeziorany' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Jędrzejów' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Jordanów' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Józefów' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Józefów' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Jutrosin' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Kalety' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Kalisz' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Kalisz Pomorski' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Kalwaria Zebrzydowska' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Kałuszyn' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Kamienna Góra' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Kamień Krajeński' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Kamień Pomorski' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Kamieńsk' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Kańczuga' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Karczew' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Kargowa' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Karlino' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Karpacz' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Kartuzy' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Katowice' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Kazimierz Dolny' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Kazimierza Wielka' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Kąty Wrocławskie' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Kcynia' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Kędzierzyn-Koźle' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Kępice' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Kępno' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Kętrzyn' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Kęty' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Kielce' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Kietrz' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Kisielice' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Kleczew' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Kleszczele' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Kluczbork' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Kłecko' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Kłobuck' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Kłodawa' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Kłodzko' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Knurów' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Knyszyn' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Kobylin' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Kobyłka' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Kock' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Kolbuszowa' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Kolno' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Kolonowskie' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Koluszki' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Kołaczyce' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Koło' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Kołobrzeg' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Koniecpol' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Konin' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Konstancin-Jeziorna' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Konstantynów Łódzki' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Końskie' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Koprzywnica' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Korfantów' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Koronowo' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Korsze' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Kosów Lacki' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Kostrzyn' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Kostrzyn nad Odrą' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Koszalin' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Kościan' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Kościerzyna' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Kowal' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Kowalewo Pomorskie' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Kowary' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Koziegłowy' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Kozienice' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Koźmin Wielkopolski' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Kożuchów' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Kórnik' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Krajenka' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Kraków' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Krapkowice' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Krasnobród' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Krasnystaw' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Kraśnik' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Krobia' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Krosno' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Krosno Odrzańskie' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Krośniewice' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Krotoszyn' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Kruszwica' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Krynica Morska' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Krynica-Zdrój' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Krynki' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Krzanowice' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Krzepice' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Krzeszowice' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Krzywiń' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Krzyż Wielkopolski' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Książ Wielkopolski' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Kudowa-Zdrój' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Kunów' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Kutno' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Kuźnia Raciborska' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Kwidzyn' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Lądek-Zdrój' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Legionowo' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Legnica' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Lesko' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Leszno' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Leśna' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Leśnica' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Lewin Brzeski' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Leżajsk' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Lębork' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Lędziny' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Libiąż' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Lidzbark' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Lidzbark Warmiński' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Limanowa' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Lipiany' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Lipno' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Lipsk' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Lipsko' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Lubaczów' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Lubań' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Lubartów' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Lubawa' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Lubawka' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Lubień Kujawski' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Lubin' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Lublin' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Lubliniec' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Lubniewice' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Lubomierz' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Luboń' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Lubraniec' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Lubsko' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Lwówek' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Lwówek Śląski' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Łabiszyn' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Łańcut' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Łapy' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Łasin' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Łask' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Łaskarzew' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Łaszczów' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Łaziska Górne' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Łazy' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Łeba' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Łęczna' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Łęczyca' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Łęknica' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Łobez' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Łobżenica' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Łochów' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Łomianki' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Łomża' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Łosice' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Łowicz' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Łódź' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Łuków' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Maków Mazowiecki' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Maków Podhalański' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Malbork' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Małogoszcz' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Małomice' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Margonin' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Marki' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Maszewo' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Miasteczko Śląskie' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Miastko' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Michałowo' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Miechów' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Miejska Górka' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Mielec' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Mieroszów' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Mieszkowice' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Międzybórz' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Międzychód' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Międzylesie' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Międzyrzec Podlaski' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Międzyrzecz' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Międzyzdroje' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Mikołajki' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Mikołów' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Mikstat' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Milanówek' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Milicz' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Miłakowo' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Miłomłyn' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Miłosław' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Mińsk Mazowiecki' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Mirosławiec' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Mirsk' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Mława' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Młynary' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Modliborzyce' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Mogielnica' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Mogilno' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Mońki' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Morąg' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Mordy' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Moryń' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Mosina' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Mrągowo' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Mrocza' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Mrozy' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Mszana Dolna' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Mszczonów' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Murowana Goślina' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Muszyna' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Mysłowice' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Myszków' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Myszyniec' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Myślenice' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Myślibórz' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Nakło nad Notecią' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Nałęczów' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Namysłów' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Narol' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Nasielsk' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Nekla' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Nidzica' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Niemcza' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Niemodlin' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Niepołomice' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Nieszawa' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Nisko' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Nowa Dęba' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Nowa Ruda' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Nowa Sarzyna' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Nowa Sól' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Nowe' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Nowe Brzesko' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Nowe Miasteczko' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Nowe Miasto Lubawskie' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Nowe Miasto nad Pilicą' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Nowe Skalmierzyce' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Nowe Warpno' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Nowogard' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Nowogrodziec' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Nowogród' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Nowogród Bobrzański' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Nowy Dwór Gdański' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Nowy Dwór Mazowiecki' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Nowy Sącz' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Nowy Staw' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Nowy Targ' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Nowy Tomyśl' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Nowy Wiśnicz' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Nysa' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Oborniki' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Oborniki Śląskie' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Obrzycko' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Odolanów' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Ogrodzieniec' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Okonek' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Olecko' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Olesno' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Oleszyce' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Oleśnica' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Olkusz' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Olsztyn' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Olsztynek' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Olszyna' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Oława' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Opalenica' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Opatów' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Opoczno' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Opole' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Opole Lubelskie' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Orneta' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Orzesze' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Orzysz' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Osieczna' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Osiek' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Ostrołęka' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Ostroróg' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Ostrowiec Świętokrzyski' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Ostróda' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Ostrów Lubelski' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Ostrów Mazowiecka' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Ostrów Wielkopolski' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Ostrzeszów' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Ośno Lubuskie' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Oświęcim' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Otmuchów' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Otwock' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Ozimek' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Ozorków' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Ożarów' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Ożarów Mazowiecki' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Pabianice' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Paczków' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Pajęczno' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Pakość' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Parczew' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Pasłęk' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Pasym' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Pelplin' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Pełczyce' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Piaseczno' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Piaski' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Piastów' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Piechowice' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Piekary Śląskie' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Pieniężno' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Pieńsk' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Pieszyce' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Pilawa' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Pilica' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Pilzno' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Piła' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Piława Górna' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Pińczów' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Pionki' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Piotrków Kujawski' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Piotrków Trybunalski' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Pisz' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Piwniczna-Zdrój' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Pleszew' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Płock' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Płońsk' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Płoty' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Pniewy' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Pobiedziska' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Poddębice' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Podkowa Leśna' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Pogorzela' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Polanica-Zdrój' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Polanów' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Police' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Polkowice' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Połaniec' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Połczyn-Zdrój' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Poniatowa' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Poniec' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Poręba' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Poznań' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Prabuty' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Praszka' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Prochowice' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Proszowice' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Prószków' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Pruchnik' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Prudnik' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Prusice' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Pruszcz Gdański' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Pruszków' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Przasnysz' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Przecław' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Przedbórz' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Przedecz' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Przemków' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Przemyśl' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Przeworsk' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Przysucha' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Pszczyna' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Pszów' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Puck' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Puławy' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Pułtusk' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Puszczykowo' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Pyrzyce' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Pyskowice' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Pyzdry' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Rabka-Zdrój' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Raciąż' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Racibórz' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Radków' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Radlin' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Radłów' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Radom' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Radomsko' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Radomyśl Wielki' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Radymno' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Radziejów' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Radzionków' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Radzymin' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Radzyń Chełmiński' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Radzyń Podlaski' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Rajgród' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Rakoniewice' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Raszków' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Rawa Mazowiecka' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Rawicz' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Recz' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Reda' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Rejowiec Fabryczny' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Resko' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Reszel' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Rogoźno' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Ropczyce' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Różan' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Ruciane-Nida' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Ruda Śląska' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Rudnik nad Sanem' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Rumia' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Rybnik' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Rychwał' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Rydułtowy' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Rydzyna' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Ryglice' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Ryki' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Rymanów' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Ryn' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Rypin' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Rzepin' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Rzeszów' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Rzgów' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Sandomierz' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Sanok' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Sejny' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Serock' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Sędziszów' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Sędziszów Małopolski' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Sępopol' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Sępólno Krajeńskie' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Sianów' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Siechnice' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Siedlce' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Siemianowice Śląskie' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Siemiatycze' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Sieniawa' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Sieradz' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Sieraków' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Sierpc' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Siewierz' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Skalbmierz' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Skała' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Skarszewy' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Skaryszew' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Skarżysko-Kamienna' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Skawina' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Skępe' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Skierniewice' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Skoczów' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Skoki' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Skórcz' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Skwierzyna' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Sława' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Sławków' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Sławno' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Słomniki' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Słubice' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Słupca' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Słupsk' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Sobótka' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Sochaczew' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Sokołów Małopolski' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Sokołów Podlaski' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Sokółka' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Solec Kujawski' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Sompolno' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Sopot' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Sosnowiec' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Sośnicowice' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Stalowa Wola' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Starachowice' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Stargard Szczeciński' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Starogard Gdański' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Stary Sącz' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Staszów' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Stawiski' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Stawiszyn' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Stąporków' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Stepnica' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Stęszew' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Stoczek Łukowski' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Stopnica' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Stronie Śląskie' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Strumień' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Stryków' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Strzegom' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Strzelce Krajeńskie' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Strzelce Opolskie' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Strzelin' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Strzelno' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Strzyżów' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Sucha Beskidzka' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Suchań' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Suchedniów' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Suchowola' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Sulechów' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Sulejów' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Sulejówek' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Sulęcin' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Sulmierzyce' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Sułkowice' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Supraśl' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Suraż' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Susz' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Suwałki' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Swarzędz' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Syców' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Szadek' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Szamocin' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Szamotuły' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Szczawnica' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Szczawno-Zdrój' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Szczebrzeszyn' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Szczecin' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Szczecinek' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Szczekociny' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Szczucin' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Szczuczyn' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Szczyrk' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Szczytna' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Szczytno' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Szepietowo' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Szklarska Poręba' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Szlichtyngowa' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Szprotawa' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Sztum' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Szubin' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Szydłowiec' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Ścinawa' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Ślesin' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Śmigiel' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Śrem' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Środa Śląska' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Środa Wielkopolska' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Świątniki Górne' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Świdnica' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Świdnik' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Świdwin' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Świebodzice' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Świebodzin' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Świecie' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Świeradów-Zdrój' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Świerzawa' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Świętochłowice' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Świnoujście' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Tarczyn' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Tarnobrzeg' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Tarnogród' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Tarnowskie Góry' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Tarnów' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Tczew' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Terespol' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Tłuszcz' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Tolkmicko' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Tomaszów Lubelski' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Tomaszów Mazowiecki' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Toruń' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Torzym' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Toszek' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Trzcianka' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Trzciel' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Trzcińsko-Zdrój' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Trzebiatów' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Trzebinia' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Trzebnica' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Trzemeszno' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Tuchola' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Tuchów' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Tuczno' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Tuliszków' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Turek' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Tuszyn' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Twardogóra' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Tychowo' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Tychy' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Tyczyn' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Tykocin' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Tyszowce' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Ujazd' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Ujście' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Ulanów' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Uniejów' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Ustka' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Ustroń' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Ustrzyki Dolne' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Wadowice' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Wałbrzych' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Wałcz' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Warka' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Warszawa' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Warta' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Wasilków' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Wąbrzeźno' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Wąchock' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Wągrowiec' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Wąsosz' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Wejherowo' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Węgliniec' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Węgorzewo' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Węgorzyno' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Węgrów' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Wiązów' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Wieleń' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Wielichowo' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Wieliczka' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Wieluń' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Wieruszów' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Więcbork' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Wilamowice' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Wisła' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Witkowo' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Witnica' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Wleń' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Władysławowo' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Włocławek' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Włodawa' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Włoszczowa' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Wodzisław Śląski' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Wojcieszów' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Wojkowice' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Wojnicz' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Wolbórz' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Wolbrom' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Wolin' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Wolsztyn' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Wołczyn' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Wołomin' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Wołów' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Woźniki' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Wrocław' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Wronki' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Września' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Wschowa' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Wyrzysk' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Wysoka' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Wysokie Mazowieckie' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Wyszków' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Wyszogród' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Wyśmierzyce' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Zabłudów' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Zabrze' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Zagórów' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Zagórz' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Zakliczyn' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Zaklików' ,'podkarpackie');
INSERT INTO locations (town, province) VALUES ('Zakopane' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Zakroczym' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Zalewo' ,'warmińsko-mazurskie');
INSERT INTO locations (town, province) VALUES ('Zambrów' ,'podlaskie');
INSERT INTO locations (town, province) VALUES ('Zamość' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Zator' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Zawadzkie' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Zawichost' ,'świętokrzyskie');
INSERT INTO locations (town, province) VALUES ('Zawidów' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Zawiercie' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Ząbki' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Ząbkowice Śląskie' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Zbąszynek' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Zbąszyń' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Zduny' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Zduńska Wola' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Zdzieszowice' ,'opolskie');
INSERT INTO locations (town, province) VALUES ('Zelów' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Zgierz' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Zgorzelec' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Zielona Góra' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Zielonka' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Ziębice' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Złocieniec' ,'zachodniopomorskie');
INSERT INTO locations (town, province) VALUES ('Złoczew' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Złotoryja' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Złotów' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Złoty Stok' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Zwierzyniec' ,'lubelskie');
INSERT INTO locations (town, province) VALUES ('Zwoleń' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Żabno' ,'małopolskie');
INSERT INTO locations (town, province) VALUES ('Żagań' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Żarki' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Żarów' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Żary' ,'lubuskie');
INSERT INTO locations (town, province) VALUES ('Żelechów' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Żerków' ,'wielkopolskie');
INSERT INTO locations (town, province) VALUES ('Żmigród' ,'dolnośląskie');
INSERT INTO locations (town, province) VALUES ('Żnin' ,'kujawsko-pomorskie');
INSERT INTO locations (town, province) VALUES ('Żory' ,'śląskie');
INSERT INTO locations (town, province) VALUES ('Żukowo' ,'pomorskie');
INSERT INTO locations (town, province) VALUES ('Żuromin' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Żychlin' ,'łódzkie');
INSERT INTO locations (town, province) VALUES ('Żyrardów' ,'mazowieckie');
INSERT INTO locations (town, province) VALUES ('Żywiec' ,'śląskie');
INSERT INTO shops_names (name, type) VALUES ('Biedronka' ,'supermarket');
INSERT INTO shops_names (name, type) VALUES ('Carrefour' ,'supermarket');
INSERT INTO shops_names (name, type) VALUES ('Lidl' ,'supermarket');
INSERT INTO shops_names (name, type) VALUES ('Auchan' ,'supermarket');
INSERT INTO shops_names (name, type) VALUES ('Kaufland' ,'supermarket');
INSERT INTO shops_names (name, type) VALUES ('InterMarche' ,'supermarket');
INSERT INTO shops_names (name, type) VALUES ('Piotr i Paweł' ,'supermarket');
INSERT INTO shops_names (name, type) VALUES ('E.Leclerc' ,'supermarket');
INSERT INTO shops_names (name, type) VALUES ('Tesco' ,'supermarket');
INSERT INTO shops_names (name, type) VALUES ('Lewiatan' ,'supermarket');
INSERT INTO shops_names (name, type) VALUES ('Żabka' ,'local');
INSERT INTO shops_names (name, type) VALUES ('Carrefour Express' ,'local');
INSERT INTO shops_names (name, type) VALUES ('ABC' ,'local');
INSERT INTO shops_names (name, type) VALUES ('Super-Pharm' ,'pharmacy, cosmetic');
INSERT INTO shops_names (name, type) VALUES ('Dom Leków' ,'pharmacy');
INSERT INTO shops_names (name, type) VALUES ('Apteka Gemini' ,'pharmacy');
INSERT INTO shops_names (name, type) VALUES ('Rossman' ,'cosmetic');
INSERT INTO shops_names (name, type) VALUES ('Natura' ,'cosmetic');
INSERT INTO statistic (queue_size) VALUES (2);
INSERT INTO statistic (queue_size) VALUES (1);
INSERT INTO statistic (queue_size) VALUES (2);
INSERT INTO statistic (queue_size) VALUES (3);
INSERT INTO statistic (queue_size) VALUES (1);
INSERT INTO availability (mask_availability, gloves_availability, gel_availability) VALUES (1,1,1);
INSERT INTO availability (mask_availability, gloves_availability, gel_availability) VALUES (2,2,2);
INSERT INTO availability (mask_availability, gloves_availability, gel_availability) VALUES (3,3,3);
INSERT INTO availability (mask_availability, gloves_availability, gel_availability) VALUES (3,2,1);
INSERT INTO availability (mask_availability, gloves_availability, gel_availability) VALUES (1,2,3);
INSERT INTO store (store_id, availability_id, statistic_id) VALUES ('858fd13c26ce3328392dda92797438f5938f87b6', 1,1);
INSERT INTO store (store_id, availability_id, statistic_id) VALUES ('fe0d80d89c5aa77138d9ffb8a16c876c18ca8210', 2,2);
INSERT INTO store (store_id, availability_id, statistic_id) VALUES ('82113b27a70a22748e7ceaef498b9d351de10ac2', 3,3);
INSERT INTO store (store_id, availability_id, statistic_id) VALUES ('24cef43fdc9a8e6ba10d9fcc93194f6647aafb12', 4,4);
INSERT INTO store (store_id, availability_id, statistic_id) VALUES ('010fd870e65f4e59d3552efe1bf3cd02e4605ced', 5,5);
