<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <title>Geolocation</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="./css/accessibilityinyourarea.css">
</head>
<body>
    <div id="map"></div>
    <script src="./js/accessibilityinyourarea.js"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyByf6Wfz_btg3iIOcdwav_UCOJGucPln4g&callback=initMap"></script>
</body>
</html>
